AMS.WebUI/Controllers/FacilityCostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AMS.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace AMS.WebUI.Controllers
{
    public class FacilityCostController : Controller
    {
        private IFacilityCostRepository facilityCostRepository;

        public FacilityCostController(IFacilityCostRepository facilityCostRepo)
        {
            facilityCostRepository = facilityCostRepo;
        }

        public ViewResult Index(QueryOptions options = null) =>
            View(facilityCostRepository.GetFilteredFacilityCosts(options));

        [HttpPost]
        public IActionResult Create([FromForm] FacilityCost facilityCost)
        {
            if (ModelState.IsValid)
            {
                facilityCostRepository.AddFacilityCost(facilityCost);
            }
            else
            {
                ViewBag.CreatedFacilityCost = facilityCost;
            }
            
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(Guid? id)
        {
            FacilityCost facilityCost;

            if(id.HasValue && (facilityCost = facilityCostRepository.GetFacilityCost(id.Value))!=null)
            {
                return View(facilityCost);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost]
        public IActionResult Update([FromForm] FacilityCost facilityCost)
        {
            if (facilityCost.UnitFacilityCosts.Sum(ufc => ufc.Share) != 100)
            {
                ModelState.AddModelError("", "مجموع سهم واحد ها صد در صد نمی شود");
            }

            if (ModelState.IsValid)
            {
                facilityCostRepository.UpdateFacilityCost(facilityCost);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(facilityCost);
            }
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            facilityCostRepository.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

AMS.WebUI/Views/Shared/PageOptions.cshtml
@model QueryOptions

<div class="container-fluid m-2">
    <div class="row m-1 p-1">
        <div class="col-8">
            <input form="pageform" class="form-control" asp-for="SearchTerm" value="@Model.SearchTerm" />
        </div>

        <div class="col-3">
            <select form="pageform" asp-for="SearchPropertyName" class="form-control">
                <option disabled selected value="">جست و جو بر اساس</option>
                <option value="Title" selected="@(Model.SearchPropertyName == "Title")">عنوان</option>
                <option value="Description" selected="@(Model.SearchPropertyName == "Description")">توضیحات</option>
            </select>
        </div>

        <div class="col-1 text-right">
            <button form="pageform" class="btn btn-secondary" type="submit">
                جست و جو
            </button>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div class="col-8 form-check text-right">
            <input form="pageform" asp-for="DescendingOrder" class="form-check-input"/>
            <label asp-for="DescendingOrder" class="form-check-label"></label>
        </div>

        <div class="col-3">
            <select form="pageform" asp-for="OrderPropertyName" class="form-control">
                <option disabled selected value="">مرتب سازی بر اساس</option>
                <option value="Title" selected="@(Model.OrderPropertyName == "Title")">عنوان</option>
                <option value="KindOfUsage" selected="@(Model.OrderPropertyName == "KindOfUsage")">نحوه استفاده</option>
                <option value="CostIncomeType" selected="@(Model.OrderPropertyName == "CostIncomeType")">درآمد/هزینه</option>
                <option value="CalculationType" selected="@(Model.OrderPropertyName == "CalculationType")">نحوه محاسبه</option>
            </select>
        </div>

        <div class="col-1 text-right">
            <button form="pageform" class="btn btn-secondary" type="submit">
                مرتب سازی
            </button>
        </div>
    </div>
</div>

AMS.WebUI/Views/Shared/Pages.cshtml
<form id="pageform" method="get" class="form-inline d-inline-block">
    <button name="options.currentPage" value="@(Model.CurrentPage - 1)" 
            class="btn btn-outline-primary" @(!Model.HasPreviousPage ? "disabled" : "") 
            type="submit">
        Previous
    </button>
    
    @for(int i = 1; i <= 3 && i <= Model.TotalPages; i++)
    {
        <button name="options.currentPage" value="@i" type="submit"
                class="btn btn-outline-primary @(Model.CurrentPage == i ? "active" :"")">
            @i
        </button>
    }
    @if(Model.CurrentPage > 3 && Model.TotalPages - Model.CurrentPage >= 3)
    {
        @:...
        <button class="btn btn-outline-primary active">@Model.CurrentPage</button>
    }
    @if (Model.TotalPages > 3)
    {
        @:...
        for (int i = Math.Max(4, Model.TotalPages - 2); i <= Model.TotalPages; i++)
        {
            <button name="options.currentPage" value="@i" type="submit"
                    class="btn btn-outline-primary @(Model.CurrentPage == i ? "active" : "")">
                @i
            </button>
        }
    }
    <button name="options.currentPage" value="@(Model.CurrentPage + 1)" type="submit"
            class="btn btn-outline-primary" @(!Model.HasNextPage ? "disabled" : "")>
        Next
    </button>
</form>

AMS.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</head>
<body style="background:#e6e6fa;">
<div class="p-2">
    <div class="navbar navbar-nav bg-purple" role="navigation">
        <a class="navbar-brand bg-info rounded text-white m-2 p-2" asp-action="Index" asp-controller="FacilityCost">سیستم مدیریت ساختمان</a>
    </div>
    <div class="row m-1 p-1">
        <div class="col">
            @RenderBody()
        </div>
    </div>
</div>
@RenderSection("scripts", false)
</body>
</html>